"""Allow assignment_id to be NULL in verification_logs

Revision ID: aae8492597af
Revises: f1df71be2bef
Create Date: 2025-03-21 22:32:53.438253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aae8492597af'
down_revision = 'f1df71be2bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.alter_column('assignment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.alter_column('assignment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
